// data.js - Categorías y palabras del juego
// Ahora con pares de palabras cercanas para el modo "Palabra cercana"

const categories = {
    animales: [
        { normal: 'león', cercana: 'tigre' },
        { normal: 'elefante', cercana: 'jirafa' },
        { normal: 'cebra', cercana: 'caballo' },
        { normal: 'mono', cercana: 'gorila' },
        { normal: 'hipopótamo', cercana: 'rinoceronte' },
        { normal: 'pingüino', cercana: 'foca' },
        { normal: 'koala', cercana: 'panda' },
        { normal: 'canguro', cercana: 'wallaby' },
        { normal: 'cocodrilo', cercana: 'caimán' },
        { normal: 'águila', cercana: 'halcón' },
        { normal: 'tiburón', cercana: 'ballena' },
        { normal: 'lobo', cercana: 'perro' },
        { normal: 'tortuga', cercana: 'galápago' },
        { normal: 'mariposa', cercana: 'polilla' },
        { normal: 'delfín', cercana: 'orca' }
    ],
    comidas: [
        { normal: 'pizza', cercana: 'empanada' },
        { normal: 'hamburguesa', cercana: 'sándwich' },
        { normal: 'sushi', cercana: 'sashimi' },
        { normal: 'tacos', cercana: 'burritos' },
        { normal: 'pasta', cercana: 'fideos' },
        { normal: 'ensalada', cercana: 'verduras' },
        { normal: 'helado', cercana: 'sorbete' },
        { normal: 'pollo', cercana: 'pavo' },
        { normal: 'carne', cercana: 'cerdo' },
        { normal: 'pescado', cercana: 'mariscos' },
        { normal: 'arroz', cercana: 'quinua' },
        { normal: 'pan', cercana: 'baguette' },
        { normal: 'queso', cercana: 'yogur' },
        { normal: 'chocolate', cercana: 'cacao' },
        { normal: 'manzana', cercana: 'pera' }
    ],
    objetos: [
        { normal: 'teléfono', cercana: 'tablet' },
        { normal: 'computadora', cercana: 'laptop' },
        { normal: 'reloj', cercana: 'cronómetro' },
        { normal: 'lápiz', cercana: 'bolígrafo' },
        { normal: 'libro', cercana: 'revista' },
        { normal: 'silla', cercana: 'banquito' },
        { normal: 'mesa', cercana: 'escritorio' },
        { normal: 'lámpara', cercana: 'foco' },
        { normal: 'teclado', cercana: 'piano' },
        { normal: 'ratón', cercana: 'trackpad' },
        { normal: 'monitor', cercana: 'televisor' },
        { normal: 'cámara', cercana: 'celular' },
        { normal: 'guitarra', cercana: 'ukelele' },
        { normal: 'bicicleta', cercana: 'moto' },
        { normal: 'sombrilla', cercana: 'parasol' }
    ],
    deportes: [
        { normal: 'fútbol', cercana: 'rugby' },
        { normal: 'baloncesto', cercana: 'voleibol' },
        { normal: 'tenis', cercana: 'ping pong' },
        { normal: 'natación', cercana: 'buceo' },
        { normal: 'atletismo', cercana: 'gimnasia' },
        { normal: 'béisbol', cercana: 'cricket' },
        { normal: 'golf', cercana: 'hockey' },
        { normal: 'ciclismo', cercana: 'patín' },
        { normal: 'boxeo', cercana: 'mma' },
        { normal: 'esquí', cercana: 'snowboard' },
        { normal: 'surf', cercana: 'bodyboard' },
        { normal: 'escalada', cercana: 'montañismo' },
        { normal: 'karate', cercana: 'taekwondo' },
        { normal: 'yoga', cercana: 'pilates' },
        { normal: 'maratón', cercana: 'cross' }
    ],
    profesiones: [
        { normal: 'médico', cercana: 'enfermero' },
        { normal: 'profesor', cercana: 'tutor' },
        { normal: 'ingeniero', cercana: 'arquitecto' },
        { normal: 'abogado', cercana: 'juez' },
        { normal: 'chef', cercana: 'cocinero' },
        { normal: 'policía', cercana: 'guardia' },
        { normal: 'bombero', cercana: 'rescatista' },
        { normal: 'piloto', cercana: 'copiloto' },
        { normal: 'dentista', cercana: 'ortodoncista' },
        { normal: 'periodista', cercana: 'escritor' },
        { normal: 'músico', cercana: 'cantante' },
        { normal: 'actor', cercana: 'modelo' },
        { normal: 'pintor', cercana: 'escultor' },
        { normal: 'fotógrafo', cercana: 'camarógrafo' },
        { normal: 'veterinario', cercana: 'zootecnista' }
    ],
    lugares: [
        { normal: 'playa', cercana: 'costa' },
        { normal: 'montaña', cercana: 'colina' },
        { normal: 'ciudad', cercana: 'pueblo' },
        { normal: 'campo', cercana: 'granja' },
        { normal: 'bosque', cercana: 'selva' },
        { normal: 'desierto', cercana: 'dunas' },
        { normal: 'isla', cercana: 'península' },
        { normal: 'río', cercana: 'arroyo' },
        { normal: 'lago', cercana: 'laguna' },
        { normal: 'parque', cercana: 'jardín' },
        { normal: 'museo', cercana: 'galería' },
        { normal: 'teatro', cercana: 'cine' },
        { normal: 'hospital', cercana: 'clínica' },
        { normal: 'escuela', cercana: 'universidad' },
        { normal: 'mercado', cercana: 'feria' }
    ],
    peliculas: [
        { normal: 'titanic', cercana: 'poseidón' },
        { normal: 'avatar', cercana: 'dune' },
        { normal: 'star wars', cercana: 'trek' },
        { normal: 'the godfather', cercana: 'goodfellas' },
        { normal: 'jurassic park', cercana: 'king kong' },
        { normal: 'harry potter', cercana: 'narnia' },
        { normal: 'the dark knight', cercana: 'iron man' },
        { normal: 'inception', cercana: 'matrix' },
        { normal: 'forrest gump', cercana: 'big fish' },
        { normal: 'pulp fiction', cercana: 'reservoir dogs' },
        { normal: 'the avengers', cercana: 'justice league' },
        { normal: 'toy story', cercana: 'shrek' },
        { normal: 'pirates', cercana: 'musketeers' },
        { normal: 'lion king', cercana: 'tarzán' },
        { normal: 'frozen', cercana: 'moana' }
    ],
    series: [
        { normal: 'breaking bad', cercana: 'weeds' },
        { normal: 'game of thrones', cercana: 'vikings' },
        { normal: 'stranger things', cercana: 'x-files' },
        { normal: 'friends', cercana: 'how i met' },
        { normal: 'the office', cercana: 'parks' },
        { normal: 'sherlock', cercana: 'elementary' },
        { normal: 'the crown', cercana: 'reign' },
        { normal: 'narcos', cercana: 'el chapo' },
        { normal: 'walking dead', cercana: 'z nation' },
        { normal: 'westworld', cercana: 'altered carbon' },
        { normal: 'money heist', cercana: 'inside man' },
        { normal: 'simpsons', cercana: 'futurama' },
        { normal: 'seinfeld', cercana: 'curb' },
        { normal: 'black mirror', cercana: 'electric dreams' },
        { normal: 'chernobyl', cercana: 'fallout' }
    ],
    animes: [
        { normal: 'naruto', cercana: 'boruto' },
        { normal: 'one piece', cercana: 'fairy tail' },
        { normal: 'dragon ball', cercana: 'saint seiya' },
        { normal: 'attack on titan', cercana: 'vinland' },
        { normal: 'my hero academia', cercana: 'black clover' },
        { normal: 'death note', cercana: 'monster' },
        { normal: 'fullmetal', cercana: 'd gray man' },
        { normal: 'sao', cercana: 'log horizon' },
        { normal: 'demon slayer', cercana: 'jujutsu' },
        { normal: 'tokyo ghoul', cercana: 'parasyte' },
        { normal: 'bleach', cercana: 'yu yu hakusho' },
        { normal: 'one punch man', cercana: 'mob psycho' },
        { normal: 'pokemon', cercana: 'digimon' },
        { normal: 'hunter x hunter', cercana: 'jojo' },
        { normal: 'cowboy bebop', cercana: 'trigun' }
    ]
};
